---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  is_file_root: true
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    # - test
  state_top:
    base:
      "*":
        - mysql
  pillars:
    top.sls:
      base:
        "*":
          - mysql

suites:
  - name: oracle-mysql-56
    provisioner:
      pillars-from-files:
        mysql.sls: tests/pillar/mysql-community-56.sls
